### ISSUE TITLE
setup-devel.yaml reseting the checked-out branches

### ISSUE THREAD

**Issue by chienandalu** [Tecnativa/doodba-scaffolding#11]
Not sure if this is really an issue:

If you checked-out different branches in the repos (i.e.: migrating some module) and run a setup-devel.yaml, the repo branch will be checkout back to the `$ODOO_MINOR` of the project. This is kind of annoying in this context :confused:

**Comment by yajo** [comment]
Yes, you need to rebuild before running setup-devel again. It's not automatic because it would slow normal operations.

Nothing else to do here, sorry :confused:
