### ISSUE TITLE
Test mails goes to wrong mailhog container

### ISSUE THREAD

**Issue by hhgabelgaard** [Tecnativa/doodba-scaffolding#18]
When running multiple test stacks (test.yaml) on different projects on the same docker host mails sent from the different odoo instances all end up in the mailhog container on the first started project.

This is because all the smtp containers is attached to the inverseproxy_shared network, and I guess the first one wins the hostname? And we need this network for the Traefik access to /smtpfake/, right?

A simple solution is of cause to rename the smtp contianer in the various projects to something unique - Or is there a more elegant solution ?

**Comment by yajo** [comment]
Thanks! Indeed a nasty bug.

The fix is in #19.
