### ISSUE TITLE
Windows Host (Docker for Windows) Support?

### ISSUE THREAD

**Issue by Cloud500** [Tecnativa/doodba-scaffolding#38]
Apparently it's not possible to use Doodba (scaffolding) on ​​Windows ...

The command
`export UID GID = "$ (id -g $ USER)" UMASK = "$ (umask)"`
is logically not available on Windows.

With and without UID, GID and UMASK (had written the Windows User ID's as Env. In the ./.env File
I always get the following error message:

```
Traceback (most recent call last):
  File "/opt/odoo/common/build", line 32, in <module>
    subprocess.check_call(command)
  File "/usr/local/lib/python3.5/subprocess.py", line 266, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
ERROR: Service 'odoo' failed to build: The command '/bin/sh -c /opt/odoo/common/build && sync' returned a non-zero code: 1
```

Is there a way to run Doodba on Windows (or is support planned?)

Would not like to use a VM with Linux for our development environment because this undermines the sense of Docker ^^

greetings
Cloud500

(Translated with Google)

**Comment by yajo** [comment]
Possibly you can use WSL to run the commands and make them work as they should, but Windows is not supported nor will be, sorry. I can't help you anymore in the matter...

Thanks!
