### ISSUE TITLE
devel DB credentials

### ISSUE THREAD

**Issue by pabloleone** [Tecnativa/doodba-scaffolding#39]
I'm not sure if this is the thread but here we go... I've installed the scaffolding, but I have no clue where to find the credentials to access de devel database autogenerated and the system fails to create a new DB. 

I presume is a very silly question but I couldn't find the credentials anywhere in the code, nor the documentation and the DB image used!

Could anyone help me with this? is there a Google channel or similar to ask this kind of questions?

Thank you.

**Comment by yajo** [comment]
Most likely you're in test or prod environment. Check this out: https://github.com/Tecnativa/doodba#adding-secrets

Actually, read the whole README. It explains all you need :wink:.
