### ISSUE TITLE
Error groupadd: GID '0' already exists

### ISSUE THREAD

**Issue by oscars8a** [Tecnativa/doodba-scaffolding#49]
https://github.com/Tecnativa/doodba-scaffolding/blob/2236a6470b1811fa8480cae39eba8b26fe05d528/common.yaml#L10

Hi I'm Oscar,
I have a little question. It is surely my fault. I have tried to instantiate an odoo 12.0 in production, with the root user. And when I launched the docker-compose -f prod.yaml build command I got the following error:
groupadd: GID '0' already exists
ERROR: Service 'odoo' failed to build
By this commit https://github.com/Tecnativa/doodba-scaffolding/commit/fa9a2e4277922a04a271a2851229691d11add9b7  I understand that it is a matter of permissions. Is it possible that I have to up the instance without using root?
PD: I have commented on the two lines and it works.
But for me it is the closest thing to black magic. :sweat_smile:

**Comment by yajo** [comment]
Just run `export UID GID="$(id -g $USER)" UMASK="$(umask)"` in the same bash shell before running `docker-compose` commands.

**Comment by oscars8a** [comment]
Thanks!
