### ISSUE TITLE
Ease the secret creation in scaffolding

### ISSUE THREAD

**Issue by gdgellatly** [Tecnativa/doodba-scaffolding#53]
Just an idea really to quickly setup these files, have an executable python file in `.` 

```
#!/usr/bin/env python3


if __name__ == '__main__':
    import os
    import secrets
    secrets_dir = '.docker'

    try:
        os.mkdir(secrets_dir, 0o700)
    except FileExistsError:
        print('.docker directory already exists ... exiting')
        exit(1)

    os.umask(0o177)

    with open(os.path.join(secrets_dir, 'odoo.env'), 'w+') as f:
        f.write(f'ADMIN_PASSWORD={secrets.token_urlsafe(10)}\n')

    pg_password = secrets.token_urlsafe(10)
    with open(os.path.join(secrets_dir, 'db-creation.env'), 'w+') as f:
        f.write(f'POSTGRES_PASSWORD={pg_password}\n')

    with open(os.path.join(secrets_dir, 'db-access.env'), 'w+') as f:
        f.write(f'PGPASSWORD={pg_password}\n')

    with open(os.path.join(secrets_dir, 'smtp.env'), 'w+') as f:
        f.write('MAIL_RELAY_PASS=\n')

    with open(os.path.join(secrets_dir, 'backup.env'), 'w+') as f:
        f.write(f'AWS_ACCESS_KEY_ID=\nAWS_SECRET_ACCESS_KEY\nPASSPHRASE={secrets.token_urlsafe(10)}')

    print(".docker skeleton file for doodba secrets created. Please edit at least "
          "smtp.env and backup.env with your environment specific details")
```

**Comment by yajo** [comment]
Hi there!

Yes, the idea seems good, although we have no plans to do this. The `devel.yaml` environment doesn't need these files, so you are good to work without them out of the box for developing.

If you're deploying to your own infrastructure any `test.yaml` or `prod.yaml` environments, it's expected that you have your own deployment system, which should handle putting secrets where they should be, and secrets handling is quite controversial so as to provide a full solution.

A good solution would be a full stack deployment solution, be that an ansible role for managing doodba instances or maybe an operator.

For the time being, as this is deployment-specific, we're probably not going to include this kind of patches.
