### ISSUE TITLE
Let's encrypt

### ISSUE THREAD

**Issue by andhit-r** [Tecnativa/doodba-scaffolding#73]
I'm having problem in obtaining Let's encrypt SSL certificate. I follow the instruction [here](https://github.com/Tecnativa/doodba/blob/master/README.md#production) but still SSL certificate shows Traefik Default Certificate.

Would you kindly point me to part of the configuration that i have to adjust or any documentation so i can solve this issue.

Many thanks.

**Comment by yajo** [comment]
Sorry this is not the place for that kind of questions. Check Traefik's support channels.
Regards.
